### ISSUE TITLE
Updating Consensus Telemetry ingesting according Flow's new consensus algorithm

### ISSUE THREAD

**Issue by AlexHentschel** [Metrika-Inc/agent#108]
Flow is updating to the Jolteon consensus protocol ([paper](https://arxiv.org/abs/2106.10362)). This is a relatively big upgrade, where also the telemetry events have been partially upgraded that the Node agent ingests. 

In the following, please find the _breaking revisions_  for Flow's [telemetry consumer](https://github.com/onflow/flow-go/blob/a3da26c56607179bf681faedc9152c8a97cba531/consensus/hotstuff/notifications/telemetry.go) that should be reflected in https://github.com/Metrika-Inc/agent/blob/main/flow/event.go:
* `OnProposingBlock` has been renamed to [`OnOwnProposal`](https://github.com/onflow/flow-go/blob/a3da26c56607179bf681faedc9152c8a97cba531/consensus/hotstuff/notifications/telemetry.go#L165-L182)
   * field `qc_block_view` has been renamed to [`qc_view`](https://github.com/onflow/flow-go/blob/a3da26c56607179bf681faedc9152c8a97cba531/consensus/hotstuff/notifications/telemetry.go#L171)
* `OnVoting`  has been renamed to [`OnOwnVote`](https://github.com/onflow/flow-go/blob/a3da26c56607179bf681faedc9152c8a97cba531/consensus/hotstuff/notifications/telemetry.go#L157-L163)
   * filed `voter_id` has been removed as this is a duplicate of `node_id `. In the context of this event, the voter is always the node itself, whose identity is already captured by `node_id `
* In `OnReceiveProposal`, the field `qc_block_view` has been renamed to [`qc_view`](https://github.com/onflow/flow-go/blob/a3da26c56607179bf681faedc9152c8a97cba531/consensus/hotstuff/notifications/telemetry.go#L58)

**Comment by AlexHentschel** [comment]
FYI: also created this issuehttps://github.com/onflow/flow-go/issues/3728 in the Flow repo for our consensus engineers to  implement. In case you come across some important aspects that the Flow team need to address, feel free to add comments there. Thanks

**Comment by iogakos** [comment]
@AlexHentschel Thank you for raising this. I opened a PR to address this in one of the upcoming releases.

**Comment by iogakos** [comment]
Resolved by https://github.com/Metrika-Inc/agent/pull/111/files.
